#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

nitrogen --restore &

picom -f &

xbacklight -set 10 &
setxkbmap latam &

if [[ $(xrandr -q | grep 'HDMI-A-0 connected')]]; then
xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --mode 1360x768 --rotate normal --right-of eDP 
fi
bspc monitor eDP -d I II III IV V
bspc monitor HDMI-A-0 -d VI VII VIII IX X

bspc config focused_border_color      '#FDCE6F'
bspc config normal_border_color       '#C9A974'
bspc config active_border_color       '#45322E'

bspc config border_width         4
bspc config window_gap          15

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a opera desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
